# ### Upload PDF
POST http://localhost:5000/api/pdf
Content-Type: application/json

{
  "title": "Integration Lecture",
  "url": "https://example.com/integration.pdf",
  "courseId": "67f44b5cf0db698b1023c194"
}

### Get All PDFs
GET http://localhost:5000/api/pdf

### Get One PDF
GET http://localhost:5000/api/pdf/67f44b70f0db698b1023c196

### Update PDF
PUT http://localhost:5000/api/pdf/67f44b70f0db698b1023c196
Content-Type: application/json

{
  "title": "Updated PDF Title"
}

### Delete PDF
DELETE http://localhost:5000/api/pdf/67f44b70f0db698b1023c196


### Search PDFs by title
GET http://localhost:5000/api/pdf/search?title=Math
Content-Type: application/json

###

### Search Courses by title
GET http://localhost:5000/api/courses/search?title=Math
Content-Type: application/json