### Create User
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "Nesrine2",
  "email": "nesrine2@example.com"
}

### Get All Users
GET http://localhost:5000/api/users

### Get One User
GET http://localhost:5000/api/users/67f44b19f0db698b1023c18e

### Update User
PUT http://localhost:5000/api/users/67f44b19f0db698b1023c18e
Content-Type: application/json

{
  "name": "Nesrine B."
}

### Delete User
DELETE http://localhost:5000/api/users/67f44b19f0db698b1023c18e